"""Semantic summarization for TIER_3 context messages.

Replaces verbatim TIER_3 messages with compact, information-dense summaries
generated by an LLM. Preserves key facts, decisions, and intent while reducing
token count to ≤20% of original.

Architecture
------------
- :class:`SemanticSummarizer` is the main entry point, registered with
  :class:`riks_context_engine.context.manager.ContextWindowManager` via
  ``set_summarizer()``.
- Summaries are stored in-place on the :class:`ContextMessage` as
  a ``summary`` attribute of type :class:`SummarizedBlock`.
- LLM calls go through :func:`_summarize_with_llm` which wraps the existing
  ollama client.

Usage
-----
    from riks_context_engine.context.manager import ContextWindowManager
    from riks_context_engine.context.summarizer import SemanticSummarizer

    mgr = ContextWindowManager()
    summarizer = SemanticSummarizer()
    mgr.set_summarizer(summarizer)

    # After normal add() calls, trigger semantic compression:
    result = summarizer.summarize_tier3(mgr)
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from riks_context_engine.context.manager import ContextMessage, ContextWindowManager

logger = logging.getLogger(__name__)

# Tier threshold for summarization (TIER_3 or lower)
SUMMARIZE_TIER_THRESHOLD = 3

# Target compression ratio: summary ≤ 20% of original token count
TARGET_COMPRESSION_RATIO = 0.20

# Minimum messages before triggering summarization
MIN_MESSAGES_FOR_SUMMARARIZATION = 4


# ---------------------------------------------------------------------------
# Extended message schema (applied at runtime via attribute injection)
# ---------------------------------------------------------------------------


@dataclass
class SummarizedBlock:
    """A compressed summary of one or more TIER_3 messages.

    Attributes
    ----------
    summary_text : str
        The LLM-generated semantic summary.
    original_ids : list[str]
        IDs of the messages that were summarized.
    original_token_count : int
        Total tokens of the original messages before compression.
    summary_token_count : int
        Tokens in the generated summary.
    compression_ratio : float
        summary_token_count / original_token_count (lower = more compression).
    generated_at : datetime
        When the summary was created.
    model : str
        LLM model used to generate the summary.
    """

    summary_text: str
    original_ids: list[str]
    original_token_count: int
    summary_token_count: int
    compression_ratio: float
    generated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    model: str = "unknown"


# ---------------------------------------------------------------------------
# LLM prompt templates
# ---------------------------------------------------------------------------

_SUMMARIZE_SYSTEM_PROMPT = """You are a precision context compressor. Your job is to distill low-importance messages into dense, information-dense summaries.

RULES:
- Extract key FACTS, DECISIONS, and USER INTENT only
- Remove filler, chitchat, and redundant repetition
- Preserve specific values, names, dates, and preferences
- Output must be ≤20% of input token count
- Write in the same language as the original messages
- Do NOT add information not present in the original
- Do NOT use bullets or headers — write as continuous prose
- If input has no signal (pure noise), return exactly: "[no signal]"
"""

_SUMMARIZE_USER_PROMPT = """Compress the following {count} messages into a single dense summary.

Messages:
---
{messages}
---

Output ONLY the compressed summary text, nothing else."""


# ---------------------------------------------------------------------------
# SemanticSummarizer class
# ---------------------------------------------------------------------------


class SemanticSummarizer:
    """LLM-based semantic summarizer for TIER_3 context messages.

    Parameters
    ----------
    llm_model : str
        Model name (default "qwen3.5-9b").
    llm_base_url : str
        Base URL for the LLM API (default "http://localhost:11434").
    min_messages : int
        Minimum TIER_3 messages before summarization is triggered.
    target_ratio : float
        Target compression ratio (summary_tokens ≤ original_tokens * ratio).
    """

    def __init__(
        self,
        llm_model: str = "qwen3.5-9b",
        llm_base_url: str = "http://localhost:11434",
        min_messages: int = MIN_MESSAGES_FOR_SUMMARARIZATION,
        target_ratio: float = TARGET_COMPRESSION_RATIO,
    ) -> None:
        self.llm_model = llm_model
        self.llm_base_url = llm_base_url
        self.min_messages = min_messages
        self.target_ratio = target_ratio

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def summarize_tier3(
        self,
        manager: ContextWindowManager,
        force: bool = False,
    ) -> SummarizationResult:
        """Find and summarize TIER_3 messages in the context window.

        Parameters
        ----------
        manager : ContextWindowManager
            The context window to operate on.
        force : bool
            If True, skip the minimum-message check.

        Returns
        -------
        SummarizationResult
            Summary of what was compressed.
        """
        # Identify TIER_3 candidates (not already summarized, not pruned)
        tier3_candidates = [
            m
            for m in manager.messages
            if m.priority_tier >= SUMMARIZE_TIER_THRESHOLD
            and not m.is_pruned
            and not hasattr(m, "summary")
        ]

        if not force and len(tier3_candidates) < self.min_messages:
            logger.debug(
                "skipping summarization: %d candidates < %d minimum",
                len(tier3_candidates),
                self.min_messages,
            )
            return SummarizationResult(
                blocks_summarized=0,
                original_tokens=0,
                summary_tokens=0,
                compression_ratio=0.0,
                summaries=[],
            )

        # Group TIER_3 messages into compressible blocks
        blocks = self._group_tier3_blocks(tier3_candidates)

        if not blocks:
            return SummarizationResult(
                blocks_summarized=0,
                original_tokens=0,
                summary_tokens=0,
                compression_ratio=0.0,
                summaries=[],
            )

        results: list[BlockSummary] = []
        total_original_tokens = 0
        total_summary_tokens = 0

        for block in blocks:
            block_msgs = [m for m in manager.messages if m.id in block]
            if not block_msgs:
                continue

            original_text = self._build_block_text(block_msgs)
            original_tokens = manager._estimate_tokens(original_text)
            target_max_tokens = int(original_tokens * self.target_ratio)

            summary_text = self._summarize_text(
                messages=original_text,
                count=len(block_msgs),
                target_max_tokens=target_max_tokens,
            )

            if summary_text == "[no signal]":
                # Mark messages as pruned instead of summarizing
                for msg in block_msgs:
                    msg.is_pruned = True
                logger.debug("block %s marked pruned (no signal)", block[:3])
                continue

            summary_tokens = manager._estimate_tokens(summary_text)
            compression = summary_tokens / original_tokens if original_tokens > 0 else 0.0

            # Store summary data on the first message in the block
            first_msg = block_msgs[0]
            first_msg.summary = SummarizedBlock(
                summary_text=summary_text,
                original_ids=block,
                original_token_count=original_tokens,
                summary_token_count=summary_tokens,
                compression_ratio=compression,
                generated_at=datetime.now(timezone.utc),
                model=self.llm_model,
            )

            # Mark remaining messages as pruned
            for msg in block_msgs[1:]:
                msg.is_pruned = True

            results.append(
                BlockSummary(
                    original_ids=block,
                    original_token_count=original_tokens,
                    summary_token_count=summary_tokens,
                    compression_ratio=compression,
                    summary_text=summary_text,
                ),
            )
            total_original_tokens += original_tokens
            total_summary_tokens += summary_tokens

        overall_ratio = (
            total_summary_tokens / total_original_tokens if total_original_tokens > 0 else 0.0
        )

        logger.info(
            "semantic summarization: %d blocks, %d→%d tokens (%.1f%%)",
            len(results),
            total_original_tokens,
            total_summary_tokens,
            overall_ratio * 100,
        )

        return SummarizationResult(
            blocks_summarized=len(results),
            original_tokens=total_original_tokens,
            summary_tokens=total_summary_tokens,
            compression_ratio=overall_ratio,
            summaries=results,
        )

    def summarize_message(self, content: str, target_max_tokens: int | None = None) -> str:
        """Summarize a single message content (standalone use)."""
        return self._summarize_text(
            messages=content,
            count=1,
            target_max_tokens=target_max_tokens or 100,
        )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _group_tier3_blocks(
        self,
        candidates: list[ContextMessage],
    ) -> list[list[str]]:
        """Group consecutive TIER_3 messages into blocks.

        A block is a sequence of adjacent TIER_3 messages.
        """
        if not candidates:
            return []

        blocks: list[list[str]] = []
        current_block: list[str] = []

        for msg in candidates:
            if not current_block:
                current_block.append(msg.id)
            else:
                current_block.append(msg.id)

        if current_block:
            blocks.append(current_block)

        return blocks

    def _build_block_text(self, messages: list[ContextMessage]) -> str:
        """Build concatenated text from a block of messages."""
        parts = []
        for m in messages:
            parts.append(f"[{m.role}] {m.content}")
        return "\n".join(parts)

    def _summarize_text(
        self,
        messages: str,
        count: int,
        target_max_tokens: int,
    ) -> str:
        """Call LLM to generate semantic summary.

        Falls back to keyword extraction if LLM is unavailable.
        """
        summary = _summarize_with_llm(
            messages=messages,
            count=count,
            target_max_tokens=target_max_tokens,
            model=self.llm_model,
            base_url=self.llm_base_url,
        )
        if summary:
            return summary

        # Fallback: extract keywords and key sentences
        return _keyword_fallback_summarize(messages, count, target_max_tokens)

    def estimate_tokens(self, text: str) -> int:
        """Estimate token count using the same method as ContextWindowManager."""
        base_tokens = len(text) / 4  # CHAR_PER_TOKEN = 4
        cjk_chars = len(re.findall(r"[\u4e00-\u9fff\u3040-\u30ff]", text))
        cjk_correction = cjk_chars - cjk_chars / 4
        return int(base_tokens + cjk_correction)


# ---------------------------------------------------------------------------
# Result dataclasses
# ---------------------------------------------------------------------------


@dataclass
class BlockSummary:
    """Summary of one compressed block."""

    original_ids: list[str]
    original_token_count: int
    summary_token_count: int
    compression_ratio: float
    summary_text: str


@dataclass
class SummarizationResult:
    """Result of a full summarization pass."""

    blocks_summarized: int
    original_tokens: int
    summary_tokens: int
    compression_ratio: float
    summaries: list[BlockSummary]


# ---------------------------------------------------------------------------
# LLM call
# ---------------------------------------------------------------------------


def _summarize_with_llm(
    messages: str,
    count: int,
    target_max_tokens: int,
    model: str,
    base_url: str,
) -> str | None:
    """Call ollama to generate a semantic summary. Returns None on failure."""
    try:
        import ollama
    except ImportError:
        logger.debug("ollama not available for summarization")
        return None

    try:
        client = ollama.Client(host=base_url, timeout=30.0)
        response = client.chat(
            model=model,
            messages=[
                {"role": "system", "content": _SUMMARIZE_SYSTEM_PROMPT},
                {
                    "role": "user",
                    "content": _SUMMARIZE_USER_PROMPT.format(
                        count=count,
                        messages=messages,
                    ),
                },
            ],
            options={
                "temperature": 0.2,
                "num_predict": max(target_max_tokens * 2, 256),
            },
        )
        content = (response.message.content or "").strip()
        # Strip markdown code fences
        if content.startswith("```"):
            content = content.split("\n", 1)[1]
        if content.endswith("```"):
            content = content.rsplit("\n", 1)[0]
        return content.strip() if content else None

    except Exception as exc:  # pragma: no cover — network, model errors
        logger.warning("LLM summarization failed: %s", exc)
        return None


# ---------------------------------------------------------------------------
# Fallback summarizer (keyword extraction)
# ---------------------------------------------------------------------------


def _keyword_fallback_summarize(
    messages: str,
    count: int,
    target_max_tokens: int,
) -> str:
    """Fallback: extract key sentences and facts without LLM."""
    # Split into sentences
    sentences = re.split(r"[.!?\n]+", messages)
    facts: list[str] = []

    # Keywords that indicate important content
    key_indicators = [
        "need",
        "want",
        "prefer",
        "use",
        "create",
        "delete",
        "update",
        "fix",
        "bug",
        "error",
        "fail",
        "success",
        "result",
        "remember",
        "don't",
        "never",
        "always",
        "config",
        "setting",
        "name",
        "date",
        "time",
        "value",
        "id",
        "email",
        "address",
    ]

    for sent in sentences:
        sent = sent.strip()
        if len(sent) < 10:
            continue
        sent_lower = sent.lower()
        if any(kw in sent_lower for kw in key_indicators):
            facts.append(sent)

    if not facts:
        # Fall back to first and last sentences
        if sentences:
            facts = [s.strip() for s in sentences[:2] if len(s.strip()) > 10]

    result = " ".join(facts[:8])  # Cap at ~8 key facts
    if not result:
        result = "[no signal]"
    return result
