#!/usr/bin/env python3
"""Generate the HTTP API reference section of docs/API.md from the OpenAPI spec.

#141 (issue #123 turn 3): docs/API.md was maintained by hand; the HTTP API
section is now generated from the FastAPI OpenAPI spec (the single source
of truth) via ``fastapi.openapi()`` (in-process — no HTTP request).

Usage:
    uv run python scripts/generate_api_md.py            # print to stdout
    uv run python scripts/generate_api_md.py --write    # regenerate docs/API.md

The generated section is placed between the sentinel comments:
    <!-- AUTO:HTTP-API:BEGIN ... -->
    <!-- AUTO:HTTP-API:END -->

Everything OUTSIDE the sentinels (installation, package entry point,
memory/context/tasks/graph/reflection modules, CLI, configuration,
exceptions) is preserved verbatim — it is manual documentation and must
NOT be touched by the generator.

The generated section contains, for every HTTP endpoint in the spec:
  - a one-line description (from the spec ``summary``/``docstring``),
  - query parameters (from the spec),
  - the request body schema (resolved from ``components/schemas``),
  - the 200 response schema (resolved),
  - example payloads (spec ``examples`` — attached by
    ``_apply_openapi_examples`` in server.py + ``Field(examples=...)``).

A generator metadata line (timestamp + generator name) is written at the
top of the section so it is obvious the section is machine-generated.

CI check (follow-up, out of scope for this PR): a CI job that runs
``--write`` in a dry run and fails when docs/API.md differs from the
generated output (i.e. someone edited the generated section by hand or
the spec changed without regenerating).
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

BEGIN = (
    "<!-- AUTO:HTTP-API:BEGIN (generated by scripts/generate_api_md.py — "
    "do not edit this section) -->"
)
END = "<!-- AUTO:HTTP-API:END -->"

FALLBACK_NOTE = (
    "> ⚠️ Auto-generated API reference unavailable — "
    "run `uv run python scripts/generate_api_md.py --write`."
)


def load_openapi() -> dict:
    """Load the FastAPI OpenAPI spec without starting the HTTP server."""
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
    from riks_context_engine.api.server import app

    spec = app.openapi()
    # Ensure the cached spec (with examples) is returned.
    assert isinstance(spec, dict)
    return spec


def _resolve_ref(spec: dict, ref: str) -> dict:
    """Resolve a ``#/components/schemas/...`` reference."""
    parts = ref.lstrip("#/").split("/")
    node: object = spec
    for part in parts:
        assert isinstance(node, dict), f"bad ref {ref!r}"
        node = node[part]
    assert isinstance(node, dict)
    return node


def _type_name(spec: dict, schema: dict) -> str:
    """Return a human-readable type name for a schema (resolving $ref)."""
    if "$ref" in schema:
        ref = schema["$ref"]
        assert isinstance(ref, str)
        return ref.rsplit("/", 1)[-1]
    ftype = schema.get("type", "object")
    if not isinstance(ftype, str):
        ftype = "object"
    if ftype == "array":
        items = schema.get("items", {})
        assert isinstance(items, dict)
        return f"list[{_type_name(spec, items)}]"
    if "anyOf" in schema:
        anyof = schema["anyOf"]
        assert isinstance(anyof, list)
        sub = [
            s for s in anyof if isinstance(s, dict) and "$ref" not in s and s.get("type") != "null"
        ]
        null = any(isinstance(s, dict) and s.get("type") == "null" for s in anyof)
        base = _type_name(spec, sub[0]) if sub else "object"
        return f"{base} | None" if null else base
    if ftype in ("integer", "number"):
        return "float" if ftype == "number" else "int"
    if ftype == "string":
        return "str"
    if ftype == "boolean":
        return "bool"
    return ftype


def _schema_to_md(spec: dict, schema: dict, depth: int = 0) -> str:
    """Render a (possibly $ref) schema as a readable markdown block."""
    if "$ref" in schema:
        resolved = _resolve_ref(spec, schema["$ref"])
        name = schema["$ref"].rsplit("/", 1)[-1]
        lines = [f"**{name}**"]
        props = resolved.get("properties", {})
        required = set(resolved.get("required", []))
        for field, fdef in props.items():
            ftype = _type_name(spec, fdef)
            default = fdef.get("default")
            desc = fdef.get("description", "")
            extra = fdef.get("enum")
            bits = []
            if default is not None:
                bits.append(f"default `{json.dumps(default)}`")
            if extra is not None:
                bits.append(f"one of {extra}")
            req = " *(required)*" if field in required else ""
            line = f"- `{field}`: `{ftype}`{req}"
            if desc:
                line += f" — {desc}"
            if bits:
                line += f" ({'; '.join(bits)})"
            lines.append(line)
        return "\n".join(lines)
    # Inline schema (e.g. an array of objects).
    ftype = schema.get("type", "object")
    if ftype == "array":
        inner = _schema_to_md(spec, schema.get("items", {}), depth + 1)
        return f"array of:\n{inner}"
    if "properties" in schema:
        lines = []
        required = set(schema.get("required", []))
        for field, fdef in schema.get("properties", {}).items():
            ftype2 = _type_name(spec, fdef)
            req = " *(required)*" if field in required else ""
            desc = fdef.get("description", "")
            line = f"- `{field}`: `{ftype2}`{req}"
            if desc:
                line += f" — {desc}"
            lines.append(line)
        return "\n".join(lines)
    return f"`{_type_name(spec, schema)}`"


def _endpoint_section(spec: dict, path: str, method: str, op: dict) -> str:
    """Render one endpoint as a markdown subsection."""
    method_u = method.upper()
    summary = op.get("summary") or (op.get("description") or "").split("\n")[0]
    lines = [f"#### `{method_u} {path}`", ""]
    if summary:
        lines += [summary, ""]

    # Query parameters.
    params = op.get("parameters", [])
    if params:
        lines.append("**Query parameters:**")
        lines.append("")
        lines.append("| Param | Type | Required | Description |")
        lines.append("|-------|------|----------|-------------|")
        for p in params:
            p_in = p.get("in", "query")
            if p_in != "query":
                continue
            ptype = (p.get("schema") or {}).get("type", "str")
            req = "yes" if p.get("required") else "no"
            desc = p.get("description", "")
            lines.append(f"| `{p.get('name')}` | `{ptype}` | {req} | {desc} |")
        lines.append("")

    # Request body.
    if "requestBody" in op:
        content = op["requestBody"].get("content", {})
        json_ct = content.get("application/json", {})
        schema = json_ct.get("schema", {})
        lines.append("**Request body:**")
        lines.append("")
        lines.append("```")
        lines.append(_schema_to_md(spec, schema))
        lines.append("```")
        examples = json_ct.get("examples", {})
        if examples:
            lines.append("")
            lines.append("**Example:**")
            lines.append("")
            lines.append("```json")
            lines.append(json.dumps(examples["default"]["value"], indent=2, ensure_ascii=False))
            lines.append("```")
        lines.append("")

    # Response.
    responses = op.get("responses", {})
    if "200" in responses:
        resp = responses["200"]
        content = resp.get("content", {})
        json_ct = content.get("application/json", {})
        schema = json_ct.get("schema", {})
        lines.append("**Response (200):**")
        lines.append("")
        lines.append("```")
        lines.append(_schema_to_md(spec, schema))
        lines.append("```")
        examples = json_ct.get("examples", {})
        if examples:
            lines.append("")
            lines.append("**Example:**")
            lines.append("")
            lines.append("```json")
            lines.append(json.dumps(examples["default"]["value"], indent=2, ensure_ascii=False))
            lines.append("```")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def build_section(spec: dict) -> str:
    """Build the full generated HTTP API section (between the sentinels)."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    title = spec.get("info", {}).get("title", "API")
    version = spec.get("info", {}).get("version", "?")
    lines = [
        BEGIN,
        "",
        f"<!-- Oluşturuldu: {now} — `scripts/generate_api_md.py` tarafından "
        "otomatik üretilmiştir, manuel düzenleme yapmayın. -->",
        "",
        f"## HTTP API (FastAPI server) — {title} v{version}",
        "",
        "> This section is **auto-generated** from the OpenAPI spec "
        "(`GET /openapi.json` / `app.openapi()`). Do not edit it by hand — "
        "regenerate with `uv run python scripts/generate_api_md.py --write`.",
        "",
        "> Interactive spec: `http://localhost:8000/docs` (Swagger) / `/redoc`.",
        "",
        "> Source: `src/riks_context_engine/api/server.py`.",
        "",
    ]

    # Endpoint overview table.
    lines.append("### Endpoint overview")
    lines.append("")
    lines.append("| Method | Path | Summary |")
    lines.append("|--------|------|---------|")
    rows = []
    for path, ops in spec.get("paths", {}).items():
        for method, op in ops.items():
            if method not in ("get", "post", "put", "patch", "delete"):
                continue
            summary = op.get("summary") or (op.get("description") or "").split("\n")[0]
            rows.append(f"| {method.upper()} | `{path}` | {summary} |")
    rows.sort()
    lines.extend(rows)
    lines.append("")

    # Per-endpoint detail.
    lines.append("### Endpoints")
    lines.append("")
    for path, ops in sorted(spec.get("paths", {}).items()):
        for method, op in ops.items():
            if method not in ("get", "post", "put", "patch", "delete"):
                continue
            lines.append(_endpoint_section(spec, path, method, op))
            lines.append("")

    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="Rewrite the generated section in docs/API.md (default: print to stdout)",
    )
    args = parser.parse_args()

    spec = load_openapi()
    section = build_section(spec)

    if not args.write:
        print(section)
        return 0

    api_md = Path(__file__).resolve().parent.parent / "docs" / "API.md"
    if not api_md.exists():
        print(f"error: {api_md} not found", file=sys.stderr)
        return 1

    text = api_md.read_text(encoding="utf-8")
    if BEGIN in text and END in text:
        start = text.index(BEGIN)
        end = text.index(END) + len(END)
        updated = text[:start] + section + text[end:]
    else:
        # No sentinels yet: insert the section before the "## CLI" heading
        # (preserving the manual sections around it).
        marker = "## CLI"
        if marker not in text:
            print(f"error: cannot find insertion point ({marker!r}) in {api_md}", file=sys.stderr)
            return 1
        idx = text.index(marker)
        updated = text[:idx] + section + "\n\n" + text[idx:]

    api_md.write_text(updated, encoding="utf-8")
    print(f"updated {api_md}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
