#!/usr/bin/env python3
"""Generate the HTTP endpoint table for docs/API.md from the OpenAPI spec.

This is the *foundation* for spec-driven API docs (see issue #123).
Full automation (regenerate + verify in CI) lands in #123; today the
script is run manually and the CI check is intentionally not enforced.

Usage:
    uv run python scripts/generate_api_docs.py            # print table to stdout
    uv run python scripts/generate_api_docs.py --write    # insert into docs/API.md

The table is placed between the sentinel comments:
    <!-- AUTO:HTTP-ENDPOINTS:BEGIN (generated by scripts/generate_api_docs.py — do not edit) -->
    <!-- AUTO:HTTP-ENDPOINTS:END -->
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

BEGIN = (
    "<!-- AUTO:HTTP-ENDPOINTS:BEGIN (generated by scripts/generate_api_docs.py — do not edit) -->"
)
END = "<!-- AUTO:HTTP-ENDPOINTS:END -->"
TABLE_HEADER = "| Method | Path | Auth | Summary |\n|--------|------|------|---------|"
FALLBACK_NOTE = "> ⚠️ Auto-generated table unavailable — run `scripts/generate_api_docs.py`."


def load_openapi() -> dict:
    """Load the FastAPI OpenAPI spec without starting the HTTP server."""
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
    from riks_context_engine.api.server import app

    return app.openapi()


def _auth_hint(method: str, path: str, spec: dict) -> str:
    """Describe auth requirements from the spec.

    Auth is enforced by middleware in server.py (X-API-Key + X-Tenant-Id),
    not OpenAPI security schemes, so describe it conservatively.
    """
    protected = path.startswith("/api/") or path in ("/", "/models")
    if not protected:
        return "none"
    tenant = "X-API-Key, X-Tenant-Id"
    return tenant if method.upper() != "GET" else f"{tenant} (if API_KEY set)"


def build_table(spec: dict) -> str:
    """Build a markdown table of all HTTP (non-WebSocket) endpoints."""
    rows: list[str] = []
    for path, ops in spec.get("paths", {}).items():
        for method, op in ops.items():
            if method not in ("get", "post", "put", "patch", "delete"):
                continue  # e.g. websocket
            summary = (op.get("summary") or op.get("description") or "").split("\n")[0]
            rows.append(
                f"| {method.upper()} | `{path}` | {_auth_hint(method, path, spec)} | {summary} |"
            )
    rows.sort()
    return "\n".join([TABLE_HEADER, *rows])


def render(spec: dict) -> str:
    try:
        table = build_table(spec)
    except Exception as exc:  # pragma: no cover - defensive fallback
        print(f"warning: could not build endpoint table: {exc}", file=sys.stderr)
        return f"{FALLBACK_NOTE}\n"
    return table


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="Rewrite the table block in docs/API.md (default: print to stdout)",
    )
    args = parser.parse_args()

    spec = load_openapi()
    block = render(spec)

    if not args.write:
        print(block)
        return 0

    api_md = Path(__file__).resolve().parent.parent / "docs" / "API.md"
    if not api_md.exists():
        print(f"error: {api_md} not found", file=sys.stderr)
        return 1

    text = api_md.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        print(
            f"error: sentinel comments not found in docs/API.md:\n{BEGIN}\n{END}",
            file=sys.stderr,
        )
        return 1

    # Replace everything between the sentinels with the freshly built table.
    start = text.index(BEGIN) + len(BEGIN)
    end = text.index(END)
    updated = text[:start] + f"\n{block}\n" + text[end:]
    api_md.write_text(updated, encoding="utf-8")
    print(f"updated {api_md} ({block.count(chr(10)) - 1} endpoint rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
